networks:
  local_network:
  central_network:

services:

  service-a:
    build: ./services/service-a
    container_name: service-a-test
    networks:
      - local_network

  service-b:
    build: ./services/service-b
    container_name: service-b-test
    networks:
      - local_network

  service-c:
    build: ./services/service-c
    container_name: service-c-test
    networks:
      - local_network

  fluent-bit:
    image: fluent/fluent-bit:3.1.9
    container_name: local-fluent-bit
    volumes:
      - ./local-logging/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./local-logging/logs:/var/log/fluentbit
    command: -c /fluent-bit/etc/fluent-bit.conf
    networks:
      - local_network
      - central_network
 
  # loki:
  #   image: grafana/loki:2.9.4
  #   container_name: loki-test
  #   command: -config.file=/etc/loki/local-config.yaml
  #   ports:
  #     - "3100:3100"
  
  # grafana:
  #   image: grafana/grafana:10.2.2
  #   container_name: grafana-test
  #   ports:
  #   - "3000:3000"
  #   depends_on:
  #   - loki
