services:
  fluent-bit:
    image: fluent/fluent-bit:3.1.9
    container_name: fluent-bit-central
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    command: -c /fluent-bit/etc/fluent-bit.conf
    restart: always
    networks:
      - central_network
