[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[FILTER]
    Name         grep
    Match        *
    # Exclude      $container_name local-fluent-bit

[OUTPUT]
    Name         forward
    Match        *
    Host         central-fluent-bit
    Port         5160

[OUTPUT]
    Name         stdout
    Match        *

[OUTPUT]
    Name          file
    Match         *
    Path          /var/log/fluentbit

# [OUTPUT]
#     Name          loki
#     Match         *
#     Host          127.0.0.1
#     Port          3100
#     Labels        job=fluentbit,container=$container_name
#     line_format   json