[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[FILTER]
    Name         grep
    Match        *
    Exclude      $container_name local-fluent-bit

# [OUTPUT]
#     Name         forward
#     Match        *
#     Host         192.168.1.19
#     Port         5160

[OUTPUT]
    Name         stdout
    Match        *

[OUTPUT]
    Name         file
    Match        *
    Path         /var/log/fluentbit