[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name        forward
    Listen      0.0.0.0
    Port        5160

[OUTPUT]
    Name            stdout
    Match           *

#[OUTPUT]
#    Name            forward
#    Match           *
#    Host            192.168.1.22
#    Port            5140
